### PR TITLE
Add a link to a list of supported locales

### PR DESCRIPTION
**Pull request by ndbroadbent**
I found a list of iOS locales on gist.github.com. I forked the Gist, fixed the CSV, and converted underscores to dashes: https://gist.github.com/ndbroadbent/b1e96c4e0137223c53d0410e060b9fc0

GitHub also makes the CSV searchable, which is pretty awesome.

### CODE REVIEW

**Comment by zoontek** [comment]
@ndbroadbent This is also an android and a windows lib. So the list should be an intersection of the languages supported by this 3 platforms

**Comment by ndbroadbent** [comment]
That's a good point, I'll try to find lists for android and windows, and will move this into the repo.

**Comment by ndbroadbent** [comment]
I updated the PR with a WIP, but I just realized that I'm probably very wrong about Windows. I know react-native-windows supports UWP apps for Windows 10, as well as WPF for Windows 7. I'm struggling to find info about those supported locales, but will keep working on this.

**Comment by ndbroadbent** [comment]
Alright, finished! I took the [Windows locales from here](https://docs.microsoft.com/en-us/windows/uwp/publish/supported-languages).

**Comment by zoontek** [comment]
@ndbroadbent Seems a lot of work to maintain this lists (Microsoft website HTML markup can change, React-Native minimum versions supported too - iOS 7 -> iOS8 was a good example)
Also, Android 5.0 seems to supports more languages than Android 4.*, etc.

Adding a language is not a thing you ara doing everyday. I'm afraid it's not worth it.

**Comment by zoontek** [comment]
Maybe you can get this tricks to export data on main platforms versions and create a small utility website?

**Pull request closed without merging**
