### PR TITLE
Fix  Cannot read property 'getLanguages' of undefined

### PR DESCRIPTION
**Pull request by giantss**
Fix  Cannot read property 'getLanguages' of undefined

### CODE REVIEW

**Comment by giantss** [comment]
#153

**Comment by LcTwisk** [comment]
This doesn’t make sense. Just linking again manually fixed the problem for me.

**Comment by giantss** [comment]
@LcTwisk The latest, some developers in accordance with the operation of the document installation is completed, run the project encountered this problem, this is not a coincidence?

**Comment by compojoom** [comment]
I get this with jest tests. Using this pull request fixed the issue for me.

**Comment by zoontek** [comment]
Thanks! Merged

**Comment by leethree** [comment]
I'm a bit confused. why not just use `RNI18n.languages` instead of `RNI18n.getLanguages()`? What's the difference between these two?

**Comment by zoontek** [comment]
@leethree `.languages` is a constant, initialized at the app boot. `getLanguages()` allow getting language at the exact instant the method is fired

**Pull request merged**
