### PR TITLE
Fix ios langauge discovery

### PR DESCRIPTION
**Pull request by ognen**
This fix loads the selected locale the app is running in properly (See http://stackoverflow.com/a/4221416).

In short, the system's locale is not necessarily the one the app is running in.

### CODE REVIEW

**Comment by zoontek** [comment]
@AlexanderZaytsev Is this library still maintened?

**Comment by AlexanderZaytsev** [comment]
@zoontek yes it's maintained by @mmazzarolo now.

**Comment by mmazzarolo** [comment]
@zoontek whoops, sorry, after having moved to another job I'm having some trouble keeping up with all the OS stuff lately  
is anybody else interested in helping me out?

**Comment by zoontek** [comment]
@AlexanderZaytsev @mmazzarolo I definitively Can help. Developing a react-native is my current job, and this package is part of the app :)

**Comment by mmazzarolo** [comment]
@zoontek it's ok for me, I have always less time for following this package.  
@AlexanderZaytsev what do you think? :)

**Comment by AlexanderZaytsev** [comment]
@zoontek @mmazzarolo I'm all for it it!

**Comment by AlexanderZaytsev** [comment]
@zoontek I sent you a collaboration invite.

**Comment by kevinhury** [comment]
any news with this PR?
It seems that detecting locale is still an issue

**Comment by msqar** [comment]
Guys, is it possible that im not being able to locate my app properly? Even though im simulating through XCode my location, it always keep the same english translations. I do have en, es and fr in my i18n.js file. How does this work? Or something is broken?

**Comment by zoontek** [comment]
@kevinhury @msqar This PR is obsolete as the current version of react-native-i18n already use `preferredLocalizations`

See:

https://github.com/AlexanderZaytsev/react-native-i18n/pull/15/commits/c8dfc1b1cc4cd228909ea5ea669db80fc6b08326#diff-8c26d8bcfaf79b734e6e8888305136a8R19

https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/RNI18n/RNI18n.m#L19

If the package is installaed correctly, try adding locales in Xcode:
https://github.com/AlexanderZaytsev/react-native-i18n/pull/15/commits/43c43c45afb79a6219f5c9428a76188d3ce5fe9d

**Comment by msqar** [comment]
@zoontek Hey Zoon, but how does this work? is this library detecting your location automatically and therefore, translating my strings? If so, how can i test this out? i would like to be able to simulate my location (i was guessing it would be inside XCode using the Location Simulator), but it wasn't working, i wanted to make sure this would work in a production version.
I know if i set the defaultLanguage within my i18n javascript, it would change the language, but i couldn't make it to detect it automatically.

Thanks in advance.

**Comment by ognen** [comment]
@zoontek Yes, the PR is now except perhaps the documentation on how to setup the Xcode project. Do you want me to clean the PR up so it's only docs?

**Comment by zoontek** [comment]
@ognen Yes, it would be awesome

**Comment by msqar** [comment]
Thank you guys, let me know so I can take a look, i added the localizations in my XCode project, tho... all the languages i'm going to support for now.

**Comment by ognen** [comment]
Done, the PR has been changed to only update the documentation.

**Comment by zoontek** [comment]
@ognen Thank you!

**Comment by msqar** [comment]
@ognen  thanks! :)

**Comment by msqar** [comment]
@ognen It's not working for me still, i did the rnpm link but i checked if the library was added, and since it wasn't, added the RNI18n.a into the library list and also in the Libraries folder it was added. Now at least im returning a locale (not being empty) which is good, but if I use the Location Simulator in XCode, i add russia, brasil, etc, but is not changing at all. What could i be missing? Thanks for your time

**Comment by msqar** [comment]
No worries, nevermind, it works. I didn't know how to simulate my locale with the iOS Simulator.

https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html

**Pull request merged**
