### PR TITLE
Added Android support

### PR DESCRIPTION
**Pull request by maraujop**
Hi Alexander,

Thanks for creating this project, It is of great help and makes it very easy to translate a react-native app. We wanted to translate Android the same way, so I decided today adding Android support.

This PR tackles #6 adding java code for bridging current locale in an Android device to javascript. Beware that Android communicates values to javascript through callbacks or events emitted, this means communication is asynchronous. 

This is my first bridge for react-native and what this means is that first render might be done with default language and for the next one the local would be already read, so interface changes, sort of flickering.

There has to be a way to come around this, but I'm currently not sure if there is one without locking. I've decided to post my progress, maybe someone can shed some light.

Let me know your thoughts, thanks.

Cheers,
Miguel

### CODE REVIEW

**Comment by Iragne** [comment]
hi just question how you integrate this module

**Comment by maraujop** [comment]
Hi @Iragne I've just updated the README, totally forgot to add this section, thanks.

**Comment by AlexanderZaytsev** [comment]
Hey @maraujop, thanks for contributing and sorry for the delay. Can you confirm your code works for Android devices right now?

**Comment by Iragne** [comment]
Hi thanks ;)

**Comment by andreipt** [comment]
Hi @AlexanderZaytsev. Are you planing to merge this pull request soon? I am very interested in using react-native-i18n for Android too. Thanks!

**Comment by AlexanderZaytsev** [comment]
@andreipt I'd love to merge it, however I can't check if this PR works with Android as is right now. If someone can confirm it works, I'll merge it.

**Comment by andreipt** [comment]
@AlexanderZaytsev, @maraujop: I just tested this PR and I can confirm it works as expected on Android.

**Comment by maraujop** [comment]
Sorry for taking so long to answer @AlexanderZaytsev . We are currently using this as it is in a product we are developing without issues, besides the async part I mentioned in my first message, which I'm not sure if it's fixable.

Thanks, cheers
Miguel

**Comment by AlexanderZaytsev** [comment]
Merged and released 0.0.7. Thanks!

**Pull request merged**
