### PR TITLE
using latest commit from i18n-js

### PR DESCRIPTION
**Pull request by hiaw**
I just copied over the latest i18n-js

### CODE REVIEW

**Comment by kenleezle** [comment]
@AlexanderZaytsev any reason this project doesn't depend on i18n-js instead of including it?

**Comment by zoontek** [comment]
@kenleezle https://github.com/fnando/i18n-js is not available on npm

**Comment by zoontek** [comment]
@kenleezle It including it essentially because of this undocumented modification: https://github.com/AlexanderZaytsev/react-native-i18n/commit/b4873738428966dfa4530e03472eb3bed53e8d6e

I don't get the point of it. Maybe @patoroco can help? If it's not useful anymore, I'll depend on i18n-js instead.

**Comment by zoontek** [comment]
i18n-js has been updated https://github.com/AlexanderZaytsev/react-native-i18n/commit/7e02f3485ee77591668a2578b2760110507dc237

**Pull request closed without merging**
