### PR TITLE
fix problem compile when set MinSDK

### PR DESCRIPTION
**Pull request by misaku**
fix problem compile when set MinSDK

### CODE REVIEW

**Comment by ralph-dev** [comment]
This issue is now more important as Gradle can't Sync without this being merged.
image

**Comment by dkwl93** [comment]
You can just remove the <uses-sdk /> tag entirely can't you?

**Comment by ralph-dev** [comment]
Yes, but the library can just delete one line instead of 10M+ people using the library all deleting the exact same line. This PR can easily be merged as per the Android Upgrade Notes

**Comment by dkwl93** [comment]
@ralph-dev No I was asking that instead of 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.AlexanderZaytsev.RNI18n">
  <uses-sdk />
</manifest>
```
Can't you just use
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.AlexanderZaytsev.RNI18n" />
```
i.e. removing the `<uses-sdk />` tag completely *from the PR* 

Absolutely agree that this should be fixed in the library

**Review by tienthanhOP — APPROVED** [review]

**Comment by AlexanderZaytsev** [comment]
Fixed in another PR.

**Pull request closed without merging**
