### PR TITLE
Remove android:minSdkVersion

### PR DESCRIPTION
**Pull request by lemankk**
Remove property android:minSdkVersion of <uses-sdk /> in AndroidManifest.xml

### CODE REVIEW

**Comment by akread** [comment]
I know this repo is deprecated but if you could please merge this and cut a release it would be wonderful. :) It is causing an issue in an app I am building as well and it is a very simple fix.

**Comment by EyMaddis** [comment]
adapt your package.json:

`"react-native-i18n": "git+https://github.com/lemankk/react-native-i18n.git#e870017bd93c9b2e3762ae83a2db3de8c4257146",`

**Comment by MaxInMoon** [comment]
Could it be done before 2020? 🙏

**Comment by nasreekar** [comment]
is this done?? Because I still have the issue and I face gradle lint error on release build because of this

**Comment by 15110011** [comment]
i dont see any android:minSdkVersion in AndroidManifest.xml but it still error

**Comment by siebeprojects** [comment]
I got the same problem, it complains about "The minSdk version should not be declared in the android manifest file". But I found an issue that solved it for me.

**Solution for me**
Recently I updated to version 2.0.15 which is available on https://www.npmjs.com/package/react-native-i18n. However, this version does not seem to be tags in this Github repository. 

After moving back to version 2.0.14 I can execute "gradle assembleRelease" again. When I changed it back again to 2.0.15 the problem of minSdk appears again. So, for now, I stick with version 2.0.14.

**Comment by zmnv** [comment]
How about updates?

**Comment by MK3690** [comment]
ERROR: The minSdk version should not be declared in the android manifest file.
in F:\Projects\myApp\node_modules\react-native-i18n\android\build.gradle

this error occur when building signed apk
"react-native-i18n": "2.0.15",

**Comment by massivespace** [comment]
This seems like a simple change.  Has this project been abandoned?

**Comment by akread** [comment]
Yes it has. See https://github.com/AlexanderZaytsev/react-native-i18n#%EF%B8%8F-this-package-is-deprecated. Temporarily, in my project, I have used [patch-package](https://www.npmjs.com/package/patch-package) to patch this. It is very easy to do. In the long run we will be replacing this package with another as it has been deprecated.

**Comment by AlexanderZaytsev** [comment]
Just fixed this in another PR.

**Comment by abo-rythm** [comment]
> Yes it has. See https://github.com/AlexanderZaytsev/react-native-i18n#%EF%B8%8F-this-package-is-deprecated. Temporarily, in my project, I have used [patch-package](https://www.npmjs.com/package/patch-package) to patch this. It is very easy to do. In the long run we will be replacing this package with another as it has been deprecated.

may you give us some hint on how to use patch-package with this one?

**Comment by nphausg** [comment]
> adapt your package.json:
> 
> `"react-native-i18n": "git+https://github.com/lemankk/react-native-i18n.git#e870017bd93c9b2e3762ae83a2db3de8c4257146",`

Absolutely thanks, it works

**Pull request closed without merging**
