### PR TITLE
Remove min-sdk from manifest

### LINKED ISSUE #220: minSDK property should be removed from manifest
Android compiling error. minSDK property should be removed from manifest.

### PR DESCRIPTION
**Pull request by andrewmarmion**
Fixes #220

### CODE REVIEW

**Comment by andrewmarmion** [comment]
@felixus95  I initially forked the repo with the fix, but I have since moved away from using this repo at all. I now use `react-native-languages` and `i18n-js`

**Comment by felixus95** [comment]
Are those better maintained? Might switch too.

**Comment by andrewmarmion** [comment]
It would appear so, both were last updated 18 days ago.
https://github.com/react-community/react-native-languages
https://github.com/fnando/i18n-js

**Comment by felixus95** [comment]
Thank you for the recommendation :)

**Comment by royderksroute42** [comment]
@AlexanderZaytsev please merge, very annoying to have to keep removing the line.

**Comment by waqas19921** [comment]
@AlexanderZaytsev should we get this.

**Comment by Sleepful** [comment]
the PR is ready but hasn't been merged, however you can add it to your `package.json` like this: https://github.com/AlexanderZaytsev/react-native-i18n/pull/258#issuecomment-516462774

**Comment by andrewmarmion** [comment]
I am closing this as this repo has now been deprecated and it does not look like it will ever be merged.

**Pull request closed without merging**
